version: '3.8'
services:
  not-a-virus-app:
    platform: linux/amd64
    container_name: 'not-a-virus-app'
    build:
      context: .
      dockerfile: Dockerfile
    image: kaenfr/not-a-virus-app:latest
    ports:
      - 4100:3000
    restart: 'unless-stopped'
    networks:
      - not-a-virus-net

networks:
  not-a-virus-net:
    name: 'not-a-virus-net'
    driver: bridge
    attachable: true
