version: '3.8'
services:
  not-a-virus-app:
    container_name: 'not-a-virus-app'
    build:
      context: .
      dockerfile: Dockerfile
    image: kaenfr/not-a-virus-app:latest
    ports:
      - 4100:3000
    depends_on:
      - postgres-notavirus
    restart: 'unless-stopped'
    networks:
      - not-a-virus-net

  postgres-notavirus:
    image: 'postgres:14.1'
    container_name: 'postgres-notavirus'
    restart: 'unless-stopped'
    ports:
      - 5432:5432
    volumes:
      - /root/docker/postgres_data:/var/lib/postgresql/data
    networks:
      - not-a-virus-net

networks:
  not-a-virus-net:
    name: 'not-a-virus-net'
    driver: bridge
    attachable: true
